//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomData.Localization {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Str {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Str() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomData.Localization.Str", typeof(Str).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Names file.
        /// </summary>
        internal static string cd_areasNamingTab_namesFile {
            get {
                return ResourceManager.GetString("cd_areasNamingTab_namesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Simple patterns file.
        /// </summary>
        internal static string cd_areasNamingTab_simplePatternFile {
            get {
                return ResourceManager.GetString("cd_areasNamingTab_simplePatternFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;i&gt;&lt;color=#FFFF00&gt;NOTE:&lt;/color&gt; Simple pattern files are like the name files, but requires to have a placeholder &quot;&lt;color=#00ff00&gt;{0}&lt;/color&gt;&quot; to be replaced by the generated name.&lt;/i&gt;.
        /// </summary>
        internal static string cd_areasNamingTab_simplePatternNote {
            get {
                return ResourceManager.GetString("cd_areasNamingTab_simplePatternNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Areas&apos; Naming.
        /// </summary>
        internal static string cd_areasNamingTab_title {
            get {
                return ResourceManager.GetString("cd_areasNamingTab_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Female given names file.
        /// </summary>
        internal static string cd_cimNamingTab_femaleNamesTitle {
            get {
                return ResourceManager.GetString("cd_cimNamingTab_femaleNamesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Male given names files.
        /// </summary>
        internal static string cd_cimNamingTab_maleNamesTitle {
            get {
                return ResourceManager.GetString("cd_cimNamingTab_maleNamesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Surnames before given names
        ///(only when using custom surnames).
        /// </summary>
        internal static string cd_cimNamingTab_surnameBeforeMainname {
            get {
                return ResourceManager.GetString("cd_cimNamingTab_surnameBeforeMainname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Surnames file.
        /// </summary>
        internal static string cd_cimNamingTab_surnamesTitle {
            get {
                return ResourceManager.GetString("cd_cimNamingTab_surnamesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cims&apos; Naming.
        /// </summary>
        internal static string cd_cimNamingTab_title {
            get {
                return ResourceManager.GetString("cd_cimNamingTab_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a City color.
        /// </summary>
        internal static string cd_districtTab_cityColor {
            get {
                return ResourceManager.GetString("cd_districtTab_cityColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a District color.
        /// </summary>
        internal static string cd_districtTab_districtColor {
            get {
                return ResourceManager.GetString("cd_districtTab_districtColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Select district.
        /// </summary>
        internal static string cd_districtTab_districtToChange {
            get {
                return ResourceManager.GetString("cd_districtTab_districtToChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Postal code digits (000 to 999).
        /// </summary>
        internal static string cd_districtTab_postalCodeDigits {
            get {
                return ResourceManager.GetString("cd_districtTab_postalCodeDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a City postal code.
        /// </summary>
        internal static string cd_districtTab_postalCodeDigitsFallback {
            get {
                return ResourceManager.GetString("cd_districtTab_postalCodeDigitsFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Road name pattern file.
        /// </summary>
        internal static string cd_districtTab_roadFormattingFile {
            get {
                return ResourceManager.GetString("cd_districtTab_roadFormattingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a City default road pattern file.
        /// </summary>
        internal static string cd_districtTab_roadFormattingFileDefault {
            get {
                return ResourceManager.GetString("cd_districtTab_roadFormattingFileDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Road naming file.
        /// </summary>
        internal static string cd_districtTab_roadNamingsFile {
            get {
                return ResourceManager.GetString("cd_districtTab_roadNamingsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a City default road naming file.
        /// </summary>
        internal static string cd_districtTab_roadNamingsFileDefault {
            get {
                return ResourceManager.GetString("cd_districtTab_roadNamingsFileDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a District data.
        /// </summary>
        internal static string cd_districtTab_title {
            get {
                return ResourceManager.GetString("cd_districtTab_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;color=#00FFFF&gt;Airport Areas&lt;/color&gt;.
        /// </summary>
        internal static string cd_Enum__DistrictAreaType_Airports {
            get {
                return ResourceManager.GetString("cd_Enum__DistrictAreaType_Airports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;color=#0044FF&gt;Liberal Arts College&lt;/color&gt;.
        /// </summary>
        internal static string cd_Enum__DistrictAreaType_Campus_Liberal {
            get {
                return ResourceManager.GetString("cd_Enum__DistrictAreaType_Campus_Liberal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;color=#0044FF&gt;University&lt;/color&gt;.
        /// </summary>
        internal static string cd_Enum__DistrictAreaType_Campus_Regular {
            get {
                return ResourceManager.GetString("cd_Enum__DistrictAreaType_Campus_Regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;color=#0044FF&gt;Trade School&lt;/color&gt;.
        /// </summary>
        internal static string cd_Enum__DistrictAreaType_Campus_Trade {
            get {
                return ResourceManager.GetString("cd_Enum__DistrictAreaType_Campus_Trade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;color=#FFFF00&gt;Farming Industry Areas&lt;/color&gt;.
        /// </summary>
        internal static string cd_Enum__DistrictAreaType_Industry_Farming {
            get {
                return ResourceManager.GetString("cd_Enum__DistrictAreaType_Industry_Farming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;color=#FFFF00&gt;Forest Industry Areas&lt;/color&gt;.
        /// </summary>
        internal static string cd_Enum__DistrictAreaType_Industry_Forest {
            get {
                return ResourceManager.GetString("cd_Enum__DistrictAreaType_Industry_Forest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;color=#FFFF00&gt;Mining Inudstry Areas&lt;/color&gt;.
        /// </summary>
        internal static string cd_Enum__DistrictAreaType_Industry_Mining {
            get {
                return ResourceManager.GetString("cd_Enum__DistrictAreaType_Industry_Mining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;color=#FFFF00&gt;Oil Industry Areas&lt;/color&gt;.
        /// </summary>
        internal static string cd_Enum__DistrictAreaType_Industry_Oil {
            get {
                return ResourceManager.GetString("cd_Enum__DistrictAreaType_Industry_Oil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;color=#00FF00&gt;Amusement Parks&lt;/color&gt;.
        /// </summary>
        internal static string cd_Enum__DistrictAreaType_Parks_Amusement {
            get {
                return ResourceManager.GetString("cd_Enum__DistrictAreaType_Parks_Amusement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;color=#00FF00&gt;City Park Areas&lt;/color&gt;.
        /// </summary>
        internal static string cd_Enum__DistrictAreaType_Parks_CityPark {
            get {
                return ResourceManager.GetString("cd_Enum__DistrictAreaType_Parks_CityPark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;color=#00FF00&gt;Natural Reserves&lt;/color&gt;.
        /// </summary>
        internal static string cd_Enum__DistrictAreaType_Parks_Natural {
            get {
                return ResourceManager.GetString("cd_Enum__DistrictAreaType_Parks_Natural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;color=#00FF00&gt;Zoo Areas&lt;/color&gt;.
        /// </summary>
        internal static string cd_Enum__DistrictAreaType_Parks_Zoo {
            get {
                return ResourceManager.GetString("cd_Enum__DistrictAreaType_Parks_Zoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;color=#888888&gt;Pedestrian Areas&lt;/color&gt;.
        /// </summary>
        internal static string cd_Enum__DistrictAreaType_Pedestrian {
            get {
                return ResourceManager.GetString("cd_Enum__DistrictAreaType_Pedestrian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Regular districts.
        /// </summary>
        internal static string cd_Enum__DistrictAreaType_Regular {
            get {
                return ResourceManager.GetString("cd_Enum__DistrictAreaType_Regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Actions.
        /// </summary>
        internal static string cd_neighborTab_actions {
            get {
                return ResourceManager.GetString("cd_neighborTab_actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Azimuth (°).
        /// </summary>
        internal static string cd_neighborTab_azimuthDirectionShort {
            get {
                return ResourceManager.GetString("cd_neighborTab_azimuthDirectionShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a City Name.
        /// </summary>
        internal static string cd_neighborTab_cityName {
            get {
                return ResourceManager.GetString("cd_neighborTab_cityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Default city names file.
        /// </summary>
        internal static string cd_neighborTab_neighborNamesFile {
            get {
                return ResourceManager.GetString("cd_neighborTab_neighborNamesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Neighbors.
        /// </summary>
        internal static string cd_neighborTab_title {
            get {
                return ResourceManager.GetString("cd_neighborTab_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data storage to extra stuff for game Intances.
        /// </summary>
        internal static string root_modDescription {
            get {
                return ResourceManager.GetString("root_modDescription", resourceCulture);
            }
        }
    }
}
