//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomData.Localization {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Str {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Str() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomData.Localization.Str", typeof(Str).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Addresses lines.
        /// </summary>
        internal static string cd_addressingSettingsTab_addressesLines {
            get {
                return ResourceManager.GetString("cd_addressingSettingsTab_addressesLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Address line 1.
        /// </summary>
        internal static string cd_addressingSettingsTab_addressLine1 {
            get {
                return ResourceManager.GetString("cd_addressingSettingsTab_addressLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Address line 2.
        /// </summary>
        internal static string cd_addressingSettingsTab_addressLine2 {
            get {
                return ResourceManager.GetString("cd_addressingSettingsTab_addressLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Address line 3.
        /// </summary>
        internal static string cd_addressingSettingsTab_addressLine3 {
            get {
                return ResourceManager.GetString("cd_addressingSettingsTab_addressLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Street name.
        /// </summary>
        internal static string cd_addressingSettingsTab_addressLineDescription_A {
            get {
                return ResourceManager.GetString("cd_addressingSettingsTab_addressLineDescription_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Number (distance from start of street).
        /// </summary>
        internal static string cd_addressingSettingsTab_addressLineDescription_B {
            get {
                return ResourceManager.GetString("cd_addressingSettingsTab_addressLineDescription_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a City Name.
        /// </summary>
        internal static string cd_addressingSettingsTab_addressLineDescription_C {
            get {
                return ResourceManager.GetString("cd_addressingSettingsTab_addressLineDescription_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a District.
        /// </summary>
        internal static string cd_addressingSettingsTab_addressLineDescription_D {
            get {
                return ResourceManager.GetString("cd_addressingSettingsTab_addressLineDescription_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Postal Code.
        /// </summary>
        internal static string cd_addressingSettingsTab_addressLineDescription_E {
            get {
                return ResourceManager.GetString("cd_addressingSettingsTab_addressLineDescription_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Special Area name (Park, industry, etc...).
        /// </summary>
        internal static string cd_addressingSettingsTab_addressLineDescription_F {
            get {
                return ResourceManager.GetString("cd_addressingSettingsTab_addressLineDescription_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a There are all letters that represents a special meaning in addresses lines.
        ///Use backslash &lt;color=#FFFF00&gt;\&lt;/color&gt; to escape a character and show it literally.
        ///The text written between brackets &lt;color=#FFFF00&gt;[ ]&lt;/color&gt; won&apos;t be shown if there&apos;s no district.
        ///The text written between parentheses &lt;color=#FFFF00&gt;( )&lt;/color&gt; won&apos;t be shown if there&apos;s no special area..
        /// </summary>
        internal static string cd_addressingSettingsTab_addressLineHelpHeaderText {
            get {
                return ResourceManager.GetString("cd_addressingSettingsTab_addressLineHelpHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a City postal code digits.
        /// </summary>
        internal static string cd_addressingSettingsTab_citywidePostalCode {
            get {
                return ResourceManager.GetString("cd_addressingSettingsTab_citywidePostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 1st digit of name seed id of the segment (0-6).
        /// </summary>
        internal static string cd_addressingSettingsTab_postalCodeDescription_A {
            get {
                return ResourceManager.GetString("cd_addressingSettingsTab_postalCodeDescription_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 2nd digit of name seed id of the segment (0-9).
        /// </summary>
        internal static string cd_addressingSettingsTab_postalCodeDescription_B {
            get {
                return ResourceManager.GetString("cd_addressingSettingsTab_postalCodeDescription_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 3rd digit of name seed id of the segment (0-9).
        /// </summary>
        internal static string cd_addressingSettingsTab_postalCodeDescription_C {
            get {
                return ResourceManager.GetString("cd_addressingSettingsTab_postalCodeDescription_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 4th digit of name seed id of the segment (0-9).
        /// </summary>
        internal static string cd_addressingSettingsTab_postalCodeDescription_D {
            get {
                return ResourceManager.GetString("cd_addressingSettingsTab_postalCodeDescription_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 5th digit of name seed id of the segment (0-9).
        /// </summary>
        internal static string cd_addressingSettingsTab_postalCodeDescription_E {
            get {
                return ResourceManager.GetString("cd_addressingSettingsTab_postalCodeDescription_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 1st digit of segment id of the segment (0-3).
        /// </summary>
        internal static string cd_addressingSettingsTab_postalCodeDescription_F {
            get {
                return ResourceManager.GetString("cd_addressingSettingsTab_postalCodeDescription_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 2nd digit of segment id of the segment (0-9).
        /// </summary>
        internal static string cd_addressingSettingsTab_postalCodeDescription_G {
            get {
                return ResourceManager.GetString("cd_addressingSettingsTab_postalCodeDescription_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 3rd digit of segment id of the segment (0-9).
        /// </summary>
        internal static string cd_addressingSettingsTab_postalCodeDescription_H {
            get {
                return ResourceManager.GetString("cd_addressingSettingsTab_postalCodeDescription_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 4th digit of segment id of the segment (0-9).
        /// </summary>
        internal static string cd_addressingSettingsTab_postalCodeDescription_I {
            get {
                return ResourceManager.GetString("cd_addressingSettingsTab_postalCodeDescription_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 5th digit of segment id of the segment (0-9).
        /// </summary>
        internal static string cd_addressingSettingsTab_postalCodeDescription_J {
            get {
                return ResourceManager.GetString("cd_addressingSettingsTab_postalCodeDescription_J", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hundreds digit from citywide postal code.
        /// </summary>
        internal static string cd_addressingSettingsTab_postalCodeDescription_K {
            get {
                return ResourceManager.GetString("cd_addressingSettingsTab_postalCodeDescription_K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tens digit from citywide postal code.
        /// </summary>
        internal static string cd_addressingSettingsTab_postalCodeDescription_L {
            get {
                return ResourceManager.GetString("cd_addressingSettingsTab_postalCodeDescription_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Units digit from citywide postal code.
        /// </summary>
        internal static string cd_addressingSettingsTab_postalCodeDescription_M {
            get {
                return ResourceManager.GetString("cd_addressingSettingsTab_postalCodeDescription_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hundreds digit from district postal code.
        /// </summary>
        internal static string cd_addressingSettingsTab_postalCodeDescription_N {
            get {
                return ResourceManager.GetString("cd_addressingSettingsTab_postalCodeDescription_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tens digit from district postal code.
        /// </summary>
        internal static string cd_addressingSettingsTab_postalCodeDescription_O {
            get {
                return ResourceManager.GetString("cd_addressingSettingsTab_postalCodeDescription_O", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Units digit from district postal code.
        /// </summary>
        internal static string cd_addressingSettingsTab_postalCodeDescription_P {
            get {
                return ResourceManager.GetString("cd_addressingSettingsTab_postalCodeDescription_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Map tile coordinate in East-West axis (0-8).
        /// </summary>
        internal static string cd_addressingSettingsTab_postalCodeDescription_X {
            get {
                return ResourceManager.GetString("cd_addressingSettingsTab_postalCodeDescription_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tenths of tile coordinate in East-West axis (0-9).
        /// </summary>
        internal static string cd_addressingSettingsTab_postalCodeDescription_x_ {
            get {
                return ResourceManager.GetString("cd_addressingSettingsTab_postalCodeDescription_x_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Map tile coordinate in North-South axis (0-8).
        /// </summary>
        internal static string cd_addressingSettingsTab_postalCodeDescription_Y {
            get {
                return ResourceManager.GetString("cd_addressingSettingsTab_postalCodeDescription_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tenths of tile coordinate in North-South axis (0-9).
        /// </summary>
        internal static string cd_addressingSettingsTab_postalCodeDescription_y_ {
            get {
                return ResourceManager.GetString("cd_addressingSettingsTab_postalCodeDescription_y_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Postal code format.
        /// </summary>
        internal static string cd_addressingSettingsTab_postalCodeFormat {
            get {
                return ResourceManager.GetString("cd_addressingSettingsTab_postalCodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a There are all letters that have a special value in the postal code formatting.
        ///Use backslash &lt;color=#FFFF00&gt;\&lt;/color&gt; to escape a character and show it literally, or put the literal content &lt;color=#FFFF00&gt;&quot;between double quotes&quot;&lt;/color&gt;.
        ///Unlisted characters will always be shown literally..
        /// </summary>
        internal static string cd_addressingSettingsTab_postalCodeHelpHeaderText {
            get {
                return ResourceManager.GetString("cd_addressingSettingsTab_postalCodeHelpHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Postal code settings.
        /// </summary>
        internal static string cd_addressingSettingsTab_postalCodeSettings {
            get {
                return ResourceManager.GetString("cd_addressingSettingsTab_postalCodeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Addressing settings.
        /// </summary>
        internal static string cd_addressingSettingsTab_title {
            get {
                return ResourceManager.GetString("cd_addressingSettingsTab_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Names file.
        /// </summary>
        internal static string cd_areasNamingTab_namesFile {
            get {
                return ResourceManager.GetString("cd_areasNamingTab_namesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Simple patterns file.
        /// </summary>
        internal static string cd_areasNamingTab_simplePatternFile {
            get {
                return ResourceManager.GetString("cd_areasNamingTab_simplePatternFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;i&gt;&lt;color=#FFFF00&gt;NOTE:&lt;/color&gt; Simple pattern files are like the name files, but requires to have a placeholder &quot;&lt;color=#00ff00&gt;{0}&lt;/color&gt;&quot; to be replaced by the generated name.&lt;/i&gt;.
        /// </summary>
        internal static string cd_areasNamingTab_simplePatternNote {
            get {
                return ResourceManager.GetString("cd_areasNamingTab_simplePatternNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Areas&apos; naming.
        /// </summary>
        internal static string cd_areasNamingTab_title {
            get {
                return ResourceManager.GetString("cd_areasNamingTab_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cargo stations.
        /// </summary>
        internal static string cd_autoNamingBuildingTab_cargoStationsNamingHeader {
            get {
                return ResourceManager.GetString("cd_autoNamingBuildingTab_cargoStationsNamingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Passenger stations.
        /// </summary>
        internal static string cd_autoNamingBuildingTab_passengerStationsNamingHeader {
            get {
                return ResourceManager.GetString("cd_autoNamingBuildingTab_passengerStationsNamingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Use address&apos; first line as name.
        /// </summary>
        internal static string cd_autoNamingBuildingTab_ricoNamingHeader {
            get {
                return ResourceManager.GetString("cd_autoNamingBuildingTab_ricoNamingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Building auto naming.
        /// </summary>
        internal static string cd_autoNamingBuildingTab_title {
            get {
                return ResourceManager.GetString("cd_autoNamingBuildingTab_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Female given names file.
        /// </summary>
        internal static string cd_cimNamingTab_femaleNamesTitle {
            get {
                return ResourceManager.GetString("cd_cimNamingTab_femaleNamesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Male given names files.
        /// </summary>
        internal static string cd_cimNamingTab_maleNamesTitle {
            get {
                return ResourceManager.GetString("cd_cimNamingTab_maleNamesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Surnames before given names
        ///(only when using custom surnames).
        /// </summary>
        internal static string cd_cimNamingTab_surnameBeforeMainname {
            get {
                return ResourceManager.GetString("cd_cimNamingTab_surnameBeforeMainname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Surnames file.
        /// </summary>
        internal static string cd_cimNamingTab_surnamesTitle {
            get {
                return ResourceManager.GetString("cd_cimNamingTab_surnamesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cims&apos; naming.
        /// </summary>
        internal static string cd_cimNamingTab_title {
            get {
                return ResourceManager.GetString("cd_cimNamingTab_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a City color.
        /// </summary>
        internal static string cd_districtTab_cityColor {
            get {
                return ResourceManager.GetString("cd_districtTab_cityColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a District color.
        /// </summary>
        internal static string cd_districtTab_districtColor {
            get {
                return ResourceManager.GetString("cd_districtTab_districtColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Select district.
        /// </summary>
        internal static string cd_districtTab_districtToChange {
            get {
                return ResourceManager.GetString("cd_districtTab_districtToChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Postal code digits (000 to 999).
        /// </summary>
        internal static string cd_districtTab_postalCodeDigits {
            get {
                return ResourceManager.GetString("cd_districtTab_postalCodeDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a City postal code.
        /// </summary>
        internal static string cd_districtTab_postalCodeDigitsFallback {
            get {
                return ResourceManager.GetString("cd_districtTab_postalCodeDigitsFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Road name pattern file.
        /// </summary>
        internal static string cd_districtTab_roadFormattingFile {
            get {
                return ResourceManager.GetString("cd_districtTab_roadFormattingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a City default road pattern file.
        /// </summary>
        internal static string cd_districtTab_roadFormattingFileDefault {
            get {
                return ResourceManager.GetString("cd_districtTab_roadFormattingFileDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Road naming file.
        /// </summary>
        internal static string cd_districtTab_roadNamingsFile {
            get {
                return ResourceManager.GetString("cd_districtTab_roadNamingsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a City default road naming file.
        /// </summary>
        internal static string cd_districtTab_roadNamingsFileDefault {
            get {
                return ResourceManager.GetString("cd_districtTab_roadNamingsFileDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a District data.
        /// </summary>
        internal static string cd_districtTab_title {
            get {
                return ResourceManager.GetString("cd_districtTab_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;color=#00FFFF&gt;Airport Areas&lt;/color&gt;.
        /// </summary>
        internal static string cd_Enum__DistrictAreaType_Airports {
            get {
                return ResourceManager.GetString("cd_Enum__DistrictAreaType_Airports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;color=#0044FF&gt;Liberal Arts College&lt;/color&gt;.
        /// </summary>
        internal static string cd_Enum__DistrictAreaType_Campus_Liberal {
            get {
                return ResourceManager.GetString("cd_Enum__DistrictAreaType_Campus_Liberal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;color=#0044FF&gt;University&lt;/color&gt;.
        /// </summary>
        internal static string cd_Enum__DistrictAreaType_Campus_Regular {
            get {
                return ResourceManager.GetString("cd_Enum__DistrictAreaType_Campus_Regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;color=#0044FF&gt;Trade School&lt;/color&gt;.
        /// </summary>
        internal static string cd_Enum__DistrictAreaType_Campus_Trade {
            get {
                return ResourceManager.GetString("cd_Enum__DistrictAreaType_Campus_Trade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;color=#FFFF00&gt;Farming Industry Areas&lt;/color&gt;.
        /// </summary>
        internal static string cd_Enum__DistrictAreaType_Industry_Farming {
            get {
                return ResourceManager.GetString("cd_Enum__DistrictAreaType_Industry_Farming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;color=#FFFF00&gt;Forest Industry Areas&lt;/color&gt;.
        /// </summary>
        internal static string cd_Enum__DistrictAreaType_Industry_Forest {
            get {
                return ResourceManager.GetString("cd_Enum__DistrictAreaType_Industry_Forest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;color=#FFFF00&gt;Mining Inudstry Areas&lt;/color&gt;.
        /// </summary>
        internal static string cd_Enum__DistrictAreaType_Industry_Mining {
            get {
                return ResourceManager.GetString("cd_Enum__DistrictAreaType_Industry_Mining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;color=#FFFF00&gt;Oil Industry Areas&lt;/color&gt;.
        /// </summary>
        internal static string cd_Enum__DistrictAreaType_Industry_Oil {
            get {
                return ResourceManager.GetString("cd_Enum__DistrictAreaType_Industry_Oil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;color=#00FF00&gt;Amusement Parks&lt;/color&gt;.
        /// </summary>
        internal static string cd_Enum__DistrictAreaType_Parks_Amusement {
            get {
                return ResourceManager.GetString("cd_Enum__DistrictAreaType_Parks_Amusement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;color=#00FF00&gt;City Park Areas&lt;/color&gt;.
        /// </summary>
        internal static string cd_Enum__DistrictAreaType_Parks_CityPark {
            get {
                return ResourceManager.GetString("cd_Enum__DistrictAreaType_Parks_CityPark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;color=#00FF00&gt;Natural Reserves&lt;/color&gt;.
        /// </summary>
        internal static string cd_Enum__DistrictAreaType_Parks_Natural {
            get {
                return ResourceManager.GetString("cd_Enum__DistrictAreaType_Parks_Natural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;color=#00FF00&gt;Zoo Areas&lt;/color&gt;.
        /// </summary>
        internal static string cd_Enum__DistrictAreaType_Parks_Zoo {
            get {
                return ResourceManager.GetString("cd_Enum__DistrictAreaType_Parks_Zoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;color=#888888&gt;Pedestrian Areas&lt;/color&gt;.
        /// </summary>
        internal static string cd_Enum__DistrictAreaType_Pedestrian {
            get {
                return ResourceManager.GetString("cd_Enum__DistrictAreaType_Pedestrian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Regular districts.
        /// </summary>
        internal static string cd_Enum__DistrictAreaType_Regular {
            get {
                return ResourceManager.GetString("cd_Enum__DistrictAreaType_Regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cargo Airports.
        /// </summary>
        internal static string cd_Enum__UseGeneratedNameCategories_AirplaneCargo {
            get {
                return ResourceManager.GetString("cd_Enum__UseGeneratedNameCategories_AirplaneCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Passenger Airports.
        /// </summary>
        internal static string cd_Enum__UseGeneratedNameCategories_AirplanePassenger {
            get {
                return ResourceManager.GetString("cd_Enum__UseGeneratedNameCategories_AirplanePassenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Blimps Stops.
        /// </summary>
        internal static string cd_Enum__UseGeneratedNameCategories_Blimps {
            get {
                return ResourceManager.GetString("cd_Enum__UseGeneratedNameCategories_Blimps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bus Stations.
        /// </summary>
        internal static string cd_Enum__UseGeneratedNameCategories_Bus {
            get {
                return ResourceManager.GetString("cd_Enum__UseGeneratedNameCategories_Bus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cable Car Buildings.
        /// </summary>
        internal static string cd_Enum__UseGeneratedNameCategories_CableCar {
            get {
                return ResourceManager.GetString("cd_Enum__UseGeneratedNameCategories_CableCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Commercial Zone.
        /// </summary>
        internal static string cd_Enum__UseGeneratedNameCategories_CommercialZone {
            get {
                return ResourceManager.GetString("cd_Enum__UseGeneratedNameCategories_CommercialZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ferryboats Harbors.
        /// </summary>
        internal static string cd_Enum__UseGeneratedNameCategories_Ferry {
            get {
                return ResourceManager.GetString("cd_Enum__UseGeneratedNameCategories_Ferry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Helicopter Stops.
        /// </summary>
        internal static string cd_Enum__UseGeneratedNameCategories_Helicopters {
            get {
                return ResourceManager.GetString("cd_Enum__UseGeneratedNameCategories_Helicopters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Industrial Zone.
        /// </summary>
        internal static string cd_Enum__UseGeneratedNameCategories_IndustrialZone {
            get {
                return ResourceManager.GetString("cd_Enum__UseGeneratedNameCategories_IndustrialZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Intercity Bus Stations.
        /// </summary>
        internal static string cd_Enum__UseGeneratedNameCategories_IntercityBus {
            get {
                return ResourceManager.GetString("cd_Enum__UseGeneratedNameCategories_IntercityBus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Metro Stations.
        /// </summary>
        internal static string cd_Enum__UseGeneratedNameCategories_Metro {
            get {
                return ResourceManager.GetString("cd_Enum__UseGeneratedNameCategories_Metro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Monorail Stations.
        /// </summary>
        internal static string cd_Enum__UseGeneratedNameCategories_Monorail {
            get {
                return ResourceManager.GetString("cd_Enum__UseGeneratedNameCategories_Monorail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Offices Zone.
        /// </summary>
        internal static string cd_Enum__UseGeneratedNameCategories_OfficeZone {
            get {
                return ResourceManager.GetString("cd_Enum__UseGeneratedNameCategories_OfficeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Residential Zone.
        /// </summary>
        internal static string cd_Enum__UseGeneratedNameCategories_ResidentialZone {
            get {
                return ResourceManager.GetString("cd_Enum__UseGeneratedNameCategories_ResidentialZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cargo Harbors.
        /// </summary>
        internal static string cd_Enum__UseGeneratedNameCategories_ShipCargo {
            get {
                return ResourceManager.GetString("cd_Enum__UseGeneratedNameCategories_ShipCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Passenger Harbors.
        /// </summary>
        internal static string cd_Enum__UseGeneratedNameCategories_ShipPassenger {
            get {
                return ResourceManager.GetString("cd_Enum__UseGeneratedNameCategories_ShipPassenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Taxi Stands.
        /// </summary>
        internal static string cd_Enum__UseGeneratedNameCategories_Taxi {
            get {
                return ResourceManager.GetString("cd_Enum__UseGeneratedNameCategories_Taxi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cargo Train Stations.
        /// </summary>
        internal static string cd_Enum__UseGeneratedNameCategories_TrainCargo {
            get {
                return ResourceManager.GetString("cd_Enum__UseGeneratedNameCategories_TrainCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Passenger Train Stations.
        /// </summary>
        internal static string cd_Enum__UseGeneratedNameCategories_TrainPassenger {
            get {
                return ResourceManager.GetString("cd_Enum__UseGeneratedNameCategories_TrainPassenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tram Stations.
        /// </summary>
        internal static string cd_Enum__UseGeneratedNameCategories_Tram {
            get {
                return ResourceManager.GetString("cd_Enum__UseGeneratedNameCategories_Tram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Trolleybus Stations.
        /// </summary>
        internal static string cd_Enum__UseGeneratedNameCategories_Trolleybus {
            get {
                return ResourceManager.GetString("cd_Enum__UseGeneratedNameCategories_Trolleybus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Actions.
        /// </summary>
        internal static string cd_neighborTab_actions {
            get {
                return ResourceManager.GetString("cd_neighborTab_actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Azimuth (°).
        /// </summary>
        internal static string cd_neighborTab_azimuthDirectionShort {
            get {
                return ResourceManager.GetString("cd_neighborTab_azimuthDirectionShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a City Name.
        /// </summary>
        internal static string cd_neighborTab_cityName {
            get {
                return ResourceManager.GetString("cd_neighborTab_cityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Default city names file.
        /// </summary>
        internal static string cd_neighborTab_neighborNamesFile {
            get {
                return ResourceManager.GetString("cd_neighborTab_neighborNamesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Neighbors.
        /// </summary>
        internal static string cd_neighborTab_title {
            get {
                return ResourceManager.GetString("cd_neighborTab_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data storage to extra stuff for game Intances.
        /// </summary>
        internal static string root_modDescription {
            get {
                return ResourceManager.GetString("root_modDescription", resourceCulture);
            }
        }
    }
}
